### ISSUE TITLE
Видео. Мобильные

### ISSUE THREAD

**Issue by npofopr** [alisabox/aleksandrbelov.ru#16]
Предложение: видео растянуть по ширине, как текст. 

![upload_2021_10_03_20_18_31_518](https://user-images.githubusercontent.com/1531751/135760463-48a3e807-be73-45d8-ac57-1689ccd767d2.jpg)

**Comment by VadimCpp** [comment]
@alisabox посмотри, пожалуйста, пример "резинового" видео на сайте:
https://vadimcpp.github.io/club111-landing/index.html

Исходники примера тут:
https://github.com/VadimCpp/club111-landing/blob/master/index.html#L96

Исправь пожалуйста

@npofopr спасибо за баг репорт, поправим

**Comment by npofopr** [comment]
Собственно и этот тоже (つ◕౪◕)つ━☆ﾟ.*･｡ﾟ
