### ISSUE TITLE
Переход к подвалу сайта

### ISSUE THREAD

**Issue by npofopr** [alisabox/aleksandrbelov.ru#17]
Предложение: убрать "дыру" между видео и футером. 
![IMG_20211003_201924](https://user-images.githubusercontent.com/1531751/135760554-91c95280-3d5a-4aeb-8dab-c1b173479686.jpg)

**Comment by VadimCpp** [comment]
@npofopr подскажите, а где дыра?

**Comment by npofopr** [comment]
> @npofopr подскажите, а где дыра?

Неправильно выразился. 
Я вот про эти переходы

![image](https://user-images.githubusercontent.com/1531751/136505014-57987e06-39d4-478e-bab7-c8126f106be7.png)

Возможно вкусовщина. 
Но кажется что если видео с серой подложкой растянуть на всю область, то можно будет скрыть чёрный треугольник между видео и футером. 

Хотя может и не стоит. 
Когда закроется #16 должно всё стать как на десктопе и наверно будет всё хорошо.

**Comment by VadimCpp** [comment]
> > @npofopr подскажите, а где дыра?
> 
> Неправильно выразился. Я вот про эти переходы
> 
> ![image](https://user-images.githubusercontent.com/1531751/136505014-57987e06-39d4-478e-bab7-c8126f106be7.png)
> 
> Возможно вкусовщина. Но кажется что если видео с серой подложкой растянуть на всю область, то можно будет скрыть чёрный треугольник между видео и футером.
> 
> Хотя может и не стоит. Когда закроется #16 должно всё стать как на десктопе и наверно будет всё хорошо.

@npofopr Владислав, спасибо большое за уточнение. Делать постановку задачи - отдельное искусство 😎

@alisabox эту задачу пока не делай, скорее всего она станет неактуальна после #16

**Comment by VadimCpp** [comment]
<img width="784" alt="Screenshot 2021-11-07 at 16 50 33" src="https://user-images.githubusercontent.com/4641125/140650022-48779117-12a1-44cb-8c04-5059de3dc5ff.png">

Исправлено.

@npofopr Владислав, проверь, пожалуйста, можно issue закрывать?

**Comment by npofopr** [comment]
Можно (つ◕౪◕)つ━☆ﾟ.*･｡ﾟ
