### ISSUE TITLE
Домен истек

### ISSUE THREAD

**Issue by VadimCpp** [alisabox/aleksandrbelov.ru#36]
Домен aleksandrbelov.ru истек и более недоступен. Прошу опубликовать сайт на githubpages и обновить ссылки в описании проекта

**Comment by alisabox** [comment]
@VadimCpp готово: [https://alisabox.github.io/aleksandrbelov.ru/](https://alisabox.github.io/aleksandrbelov.ru/)
Только сейчас заметила эту задачку, похоже GitHub присылает уведомления только если тегать по имени напрямую.
